alias pmv='/home/milesm/Publications/XGBScore/SCORCH/utils/MGLTools-1.5.6/bin/pmv'
alias adt='/home/milesm/Publications/XGBScore/SCORCH/utils/MGLTools-1.5.6/bin/adt'
alias vision='/home/milesm/Publications/XGBScore/SCORCH/utils/MGLTools-1.5.6/bin/vision'
alias cadd='/home/milesm/Publications/XGBScore/SCORCH/utils/MGLTools-1.5.6/bin/cadd'
alias pythonsh='/home/milesm/Publications/XGBScore/SCORCH/utils/MGLTools-1.5.6/bin/pythonsh'
